
package analisadorlexico;


public enum Token {
    PALAVRA,OPERADOR_ARITMETICO, OPERADOR_LOGICO,OP_ATRIBUICAO, OP_RELACIONAL, OP_BOOLEANO, SEPARADOR, 
    ESPECIAL, COMENTARIO,LINHA, ID,NUMERO, ERROR, INICIO, FIM,CADEIACARAC,REAL
}

